### ISSUE TITLE
A request

### ISSUE THREAD

**Issue by iRuizeWu** [RaptorMai/iccv_cl_2021#1]
Hello, sorry to bother you, I would like to ask if you have any draft articles about your team in this competition that you can refer to and study? I didn't find it on arxiv. Thank you very much, even if it is inconvenient.

**Comment by RaptorMai** [comment]
Could you send me an email? We can discuss it in a bit more detail.

**Comment by iRuizeWu** [comment]
Ok, i have sent you an email.
